export const handleError = (error, errorBlock) => {
    console.log(`Error occurs inside ${errorBlock}: ${error}`)
}